### ISSUE TITLE
Setup & Running Ethereum, Polygon, BSC full-node

### ISSUE THREAD

**Issue by taijusanagi** [taijusanagi/taijusanagi.com#1]
## Background
- I was using [infura.io](https://infura.io/) free plan, but recently my services usage exceeds free plan limitation
- I realized BSC and Polygon public node query has limitation, such as number of event limitation

## My thought
- Self running full node may be cost efficient
- Running self node may be required for newly coming chain development

## This issue describe...
- How to setup full node for each chain
- Running result

**Comment by taijusanagi** [comment]
## Infrastructure
- This node can be used for new business so separate project is created
- This project is named as Chocoserver, this includes blockchain node and synced database
- GCP is used because I'm familiar with GCP

**Comment by taijusanagi** [comment]
## Ethereum Mainnet

### Ethereum Full Node Sync
https://etherscan.io/chartsync/chaindefault

**Comment by taijusanagi** [comment]
### Polygon
https://docs.matic.network/docs/develop/network-details/full-node-deployment

**Comment by taijusanagi** [comment]
### BSC

**Comment by taijusanagi** [comment]
Ubuntu 1804は最初からpython3が入っている

```
Command 'python' not found, but can be installed with:
apt install python3       
apt install python        
apt install python-minimal
Ask your administrator to install one of them.
You also have python3 installed, you can run 'python3' instead.
```

Aliasはここを参照した
https://qiita.com/houtarou/items/c7fa8006eef9e30ffad5

**Comment by taijusanagi** [comment]
When instll ansible, I faced this issue

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ozh26v_c/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
```

**Comment by taijusanagi** [comment]
### Issue

```
Command 'ansible' not found, but can be installed with:
apt install ansible
Please ask your administrator.
```

### Fix
https://github.com/ansible/ansible/issues/67259

added following to ~/.bashrc
```
export PATH=$PATH:~/.local/bin
```

**Comment by taijusanagi** [comment]
Further Polygon architecture investigation is here
https://github.com/taijusanagi/taijusanagi.com/issues/11

**Comment by taijusanagi** [comment]
### Issue
Ethereum mainnet node

```
curl --location --request POST 'localhost:8545/' --header 'Content-Type: application/json' --data-raw '{
"jsonrpc":"2.0",
"method":"eth_syncing",
"params":[],
"id":1
}'
curl: (56) Recv failure: Connection reset by peer
```

### Fix
https://ethereum.stackexchange.com/questions/48272/can-i-curl-a-full-node-on-initial-sync

**Comment by taijusanagi** [comment]
Setup firewall for gce
https://stackoverflow.com/questions/21065922/how-to-open-a-specific-port-such-as-9090-in-google-compute-engine

**Comment by taijusanagi** [comment]
### Issue
```
Command 'geth' not found
```

### Fix
https://github.com/ethereum/go-ethereum/issues/14644

run below instead of geth
```
./build/bin/geth
```

**Comment by taijusanagi** [comment]
### Issue
after ```geth --datadir node init genesis.json```

```
ERROR[04-17|09:31:28.798] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed 
to initialize libusb: libusb: unknown error [code -99]"
ERROR[04-17|09:31:28.798] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed 
to initialize libusb: libusb: unknown error [code -99]"
ERROR[04-17|09:31:28.798] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed 
to initialize libusb: libusb: unknown error [code -99]"
ERROR[04-17|09:31:28.799] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed 
to initialize libusb: libusb: unknown error [code -99]"
ERROR[04-17|09:31:28.799] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed 
to initialize libusb: libusb: unknown error [code -99]"
ERROR[04-17|09:31:28.799] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed 
to initialize libusb: libusb: unknown error [code -99]"
```

**Comment by taijusanagi** [comment]
### make geth background process
```
https://ethereum.stackexchange.com/questions/366/how-can-i-run-go-ethereum-as-daemon-process-on-ubuntu
```

**Comment by taijusanagi** [comment]
### IP Address 
this is at 20210417

```
bsc: 35.189.146.191
ethereum: 34.84.175.247
polygon: 35.221.68.203
```

**Comment by taijusanagi** [comment]
```
HTTPHost = "0.0.0.0"
HTTPVirtualHosts = ["0.0.0.0"]
```

**Comment by taijusanagi** [comment]
### Further discuss
https://github.com/taijusanagi/taijusanagi.com/issues/12

**Comment by taijusanagi** [comment]
updated command for https://github.com/taijusanagi/taijusanagi.com/issues/13#issuecomment-821804822

**Comment by taijusanagi** [comment]
Bug fix
https://github.com/chocomintapp/chocoserver/issues/12#issue-860839610
